#ifndef GAME_HEADERS_H
#define GAME_HEADERS_H

extern bool boundingSphereOn;

#include "Framework.h"
#include "Game.h"
#include "GameObject.h"
#include "MathEngine.h"
#include "ShaderObject.h"
#include "CubeModel.h"
#include "GraphicsObject.h"
#include "GraphicsObject_ColorByPosition.h"
#include "GraphicsObject_Wireframe.h"
#include "GraphicsObject_FlatTexture.h"
#include "GraphicsObject_TextureLight.h"
#include "Texture.h"
#include "InputMan.h"
#include "InputTest.h"
#include "CameraMan.h"
#include "CameraNode.h"
#include "Camera.h"
#include "CameraModel.h"
#include "CameraDemoInput.h"
#include "GameObjectMan.h"
#include "ModelMan.h"
#include "ShaderMan.h"
#include "SphereModel.h"
#include "PyramidModel.h"
#include "2Pyramids.h"
#include "GraphObj_SimpleColor.h"
#include "GraphObj_ColorLight.h"
#include "CustomModel.h"
#include "RitterSphereModel.h"
#include "GraphicsObject_WireframeConstantColor.h"
#include"SimpleGameObject.h"
#include"BoundingSphereGameObject.h"
#include "GameTime.h"
#include "Timer.h"
#include "VectApp.h"
#include "QuatApp.h"
#include "FrameMan.h"
#include "GameObjectAnim.h"
#include "NullModel.h"
#include "GameObjectRigid.h"
#include"GraphicsObject_Null.h"
#include "ClipMan.h"
#include "AnimControllerTeddy.h"
#include "AnimControllerHuman.h"
#include "AnimMan.h"
#include "KeyDemo.h"
#include "SpriteModel.h"
#include "ImageMan.h"
#include "GraphicsObject_Sprite.h"
#include "GameObject2D.h"
#include "GlyphMan.h"
#include <string>
#include <sstream>
#include "SkinModel.h"
#include "FontMan.h"
#include "GlyphMan.h"
#include"GameObject2DFont.h"
#include"GraphicsObjectFont.h"
#include "ComputeBone.h"
#include"SSBO_MAN.h"
#endif

// --- End of File --------------------------------------------------